name: Flutter CI

on:
  push:
    branches: [taufik]
  pull_request:
    branches: [taufik]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.6" # versi kamu
          channel: "stable"

      # Install dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # Analyze code (lint)
      - name: Flutter Analyze
        run: flutter analyze

      # Run unit tests
      - name: Flutter Test
        run: flutter test
